#!/bin/bash
set -e -x
if [ -n "$TLS_DOMAIN" ]
then
  TLS_DOMAINS=$TLS_DOMAIN
fi

if [ $(find /etc/letsencrypt -name '*.cmd' | wc -l) -gt 0 ]
then 
  echo "Clean up old /etc/letsencrypt configuration"
  rm -rf /etc/letsencrypt/*
fi

if [ -n "$TLS_DOMAINS" ]
then
  for DOMAIN in $TLS_DOMAINS
  do
    if [ -d /etc/letsencrypt/archive/$DOMAIN ] 
    then
      certbot renew
    else
      certbot certonly --noninteractive --standalone -d $DOMAIN --agree-tos --email $TLS_EMAIL
    fi
  done
fi

(/etc/init.d/nginx configtest || cat /var/log/nginx/error.log)
exec /etc/init.d/nginx start
