#!/bin/bash
set -e -x
if [ -n "$TLS_DOMAIN" ]
then
  if [ -d /etc/letsencrypt/archive ] 
  then
    letsencrypt renew
  else
    letsencrypt certonly --noninteractive --standalone -d $TLS_DOMAIN --agree-tos --email $TLS_EMAIL
  fi
fi
exec /etc/init.d/nginx start
